import fs from 'node:fs';
import path from 'node:path';

/**
 * Build-time loader for data/dividends.json (generated by the overseas-sites
 * repo's scripts/render_dividend_data.py from Yahoo chart data). Refreshed on
 * a ~bi-weekly cadence, so pages can show "current" distribution dates and
 * yields for the ticker calendar blogs.
 */

export interface TickerDividendData {
  cadence: 'monthly' | 'quarterly' | 'annual' | string;
  cadenceDays: number;
  lastExDate: string;
  lastAmount: number;
  recent3: { exDate: string; amount: number }[];
  projectedNext: string[];
  price: number | null;
  ttmYieldPct: number | null;
  source: string;
}

interface DividendsFile {
  asOf: string;
  tickers: Record<string, TickerDividendData>;
}

function load(): DividendsFile | undefined {
  try {
    const raw = fs.readFileSync(path.join(process.cwd(), 'data', 'dividends.json'), 'utf-8');
    const parsed = JSON.parse(raw) as DividendsFile;
    return parsed.asOf && parsed.tickers ? parsed : undefined;
  } catch {
    // File missing/corrupt: render without the dynamic block (silent degrade).
    return undefined;
  }
}

const DATA = load();

export function getDividendsAsOf(): string | undefined {
  return DATA?.asOf;
}

export function getTickerData(ticker: string): TickerDividendData | undefined {
  return DATA?.tickers[ticker.toUpperCase()];
}
